### ISSUE TITLE
Unable to add probonopd/TimeLord library via libraries.txt nor by file upload

### ISSUE THREAD

**Issue by DavidThijs** [wokwi/wokwi-features#224]
**Is your feature request related to a problem? Please describe.**

Attempted to add TimeLord to the libraries.txt file but it results in a compile error
Attempted to add Timelord.h to the files but the library can still not be found
Source: https://github.com/probonopd/TimeLord

**Describe the solution you'd like**
A possibility to reference less known or popular libraries by adding them to the set of files

**Comment by leftCoast** [comment]
It doesn't look like this was ever added to the Arduino IDE library list. Does the libraries.txt list feature work on libraries NOT on the IDE list?

**Comment by urish** [comment]
libraries.txt only works for libraries that are available in the Arduino Library Manager.

You can still use the library by copying the files into your project. In this case, you'll have to change the #include statements to use " " instead of < >. Here's an example for the [TimeLord](https://github.com/probonopd/TimeLord) library:

https://wokwi.com/arduino/projects/314584182162457154

**Comment by DavidThijs** [comment]
Thanks a lot, including the libraries with the "" instead of the <> did the job !
