### ISSUE TITLE
Analog temperature sensor and analog potentiometer working incorrectly when not properly powered

### ISSUE THREAD

**Issue by juiba2** [wokwi/wokwi-features#288]
I'm trying to test run reading multiple analog sensor values by using only one pin by following this example: https://create.arduino.cc/projecthub/e_s_c/how-to-read-multiple-analog-values-using-one-analog-pin-f5f6db

However, when selecting either analog temperature sensor or analog potentiometer, I'm not able to run this correctly. It turned out that actually both of the sensors are working even without VCC and GND pins are not connected, e.g. you are able to read correct values from the sensor just by connecting OUT/SIG pin to the A0. Of course, in real life it doesn't work that way.

My understanding is that at least analog temperature sensor and analog potentiometer are working incorrectly by supplying data without properly powered.

**Comment by urish** [comment]
Thanks for the report!

Wokwi isn't a full analog circuit simulator - it only has basic support for several analog sensors. There are several open request / suggestions to enhance the analog simulation (#203, #247, #97). 

If you do need full analog circuit simulation (e.g. for the project you mentioned), then [Circuit.js + AVR8js](https://www.falstad.com/circuit/avr8js/) may be a good fit.

Closing this issue as this is the expected behavior in the current implementation of the simulator. If at some point we implement better analog circuit simulation, this will likely to be resolved as part of that future implementation.
