### ISSUE TITLE
A new component is not dropped onto the grid (with the grid turned on).

### ISSUE THREAD

**Issue by Koepel** [wokwi/wokwi-features#443]
When the grid is turned on, and a new component is selected, it is not dropped onto the grid locations.
Clicking on the new component makes it snap onto the grid. That little snap is confusing because something happened and it is unknown for new users what just happened.

**Comment by urish** [comment]
Note: I'm still looking into this. It's a bit tricky to solve, since we align the components to the grid based on their pin positions (we actually align the pins to the grid), but we can't know the pin positions until we draw the component (due to the way wokwi-elements works and the fact that the pin positions can change depending on attribute values). That's why it'll take longer until we get this one fixed.

**Comment by urish** [comment]
All new parts are now aligned to grid by default. Would love to get some feedback on this!

**Comment by Koepel** [comment]
It works very well.
