### ISSUE TITLE
Documentation bug: Missing neopixel elements

### ISSUE THREAD

**Issue by M-square** [wokwi/wokwi-features#447]
There are three neopixel items is in the add-component-dropdown, but not in the documentation.

In addition, I have an (old) project where I used wokwi-neopixel-matrix. I am sure it was documented then, but now it isn't even in the dropdown. The project works fine : https://wokwi.com/projects/316533974926099009

**Comment by urish** [comment]
Yea, they never made it to the documentation. The reason is that they are a mess - neopixel-matrix has no visible pins, and terrible performance. neopixel-canvas is better, but its name is confusing. 

So basically waiting for #240. It recently got a nice amount of [votes](https://wokwi.com/features#feature-1079348122), so I hope we'll get to it soon.
