### ISSUE TITLE
CoAP help i can't connect

### ISSUE THREAD

**Issue by AtmajaNam1** [wokwi/wokwi-features#572]
**Describe the bug**
CoAP DHT11.ino:19:1: error: 'coap_resource_t' does not name a type
 coap_resource_t* temperature_resource = NULL;
 ^~~~~~~~~~~~~~~
CoAP DHT11.ino:20:1: error: 'coap_resource_t' does not name a type
 coap_resource_t* humidity_resource = NULL;
 ^~~~~~~~~~~~~~~
CoAP DHT11.ino:38:26: error: 'coap_packet_t' does not name a type; did you mean 'CoapPacket'?
 void coap_callback(const coap_packet_t* packet, uint8_t method, coap_response_t* response) {
                          ^~~~~~~~~~~~~
                          CoapPacket
CoAP DHT11.ino:38:65: error: 'coap_response_t' has not been declared
 void coap_callback(const coap_packet_t* packet, uint8_t method, coap_response_t* response) {
                                                                 ^~~~~~~~~~~~~~~

**To Reproduce**
[Steps to reproduce the behavior, including link to a simulation project where we can see the problem.](https://wokwi.com/projects/360514617542572033)

**Expected behavior**

**Environment (please complete the following information):**
 - Browser [Chrome]

**Additional context**
can't connect coap thingsboard

**Comment by urish** [comment]
Hello, there is no issue with the simulator.

The code won't compile since you are using code that is not compatible with the "CoAP simple library" in your project. You can check out the examples of "CoAP simple library" to learn more about how to use it:

https://github.com/hirotakaster/CoAP-simple-library/blob/master/examples/esp32/esp32.ino
