### ISSUE TITLE
Neopixel/WS2812

### ISSUE THREAD

**Issue by LeonBoettcher** [wokwi/wokwi-features#621]
**Is your feature request related to a problem? Please describe.**
IF you want to simulate mor than a Ws2812 Addrresable LED Ring you would need to place the single LEDs which is not easy.

**Describe the solution you'd like**
A 10 LEDs Neopixel /WS2812 stripe with 5V,GND,DIN,Dout with the possibility to connect those

**Comment by sutaburosu** [comment]
Addressable RGB strips and matrices are already available in the simulator, but they are not documented yet.  To use them, [see this issue for example JSON snippets](https://github.com/wokwi/wokwi-features/issues/237) to add to your `diagram.json`.

The documentation will catch up after [the work in progress to unify all the addressable LED types is completed](https://github.com/wokwi/wokwi-features/issues/240). You can [vote for this issue here](https://wokwi.com/features#feature-1079348122).
