### ISSUE TITLE
Please return support for ESP8266 hardware

### ISSUE THREAD

**Issue by joakimgk** [wokwi/wokwi-features#646]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by urish** [comment]
We never had support for ESP8266 :-) 

The request to add ESP8266 is tracked as #314. However, it's not very likely to happen, since ESP8266 is being [replaced by ESP32-C3](https://www.hackster.io/news/espressif-s-esp32-c3-leaks-as-a-drop-in-pin-compatible-risc-v-replacement-for-the-popular-esp8266-f535223d7e68)
