### ISSUE TITLE
Add option to visualize memory access errors (e.g. array out of bounds)

### ISSUE THREAD

**Issue by ooomens** [wokwi/wokwi-features#68]
For learning with Wokwi it would be really helpful if we had an option to enable warnings when something like memory access to an array out of its bounds happens. Makes debugging weird behavior a lot easier.

Cheers

**Comment by urish** [comment]
I'm thinking how to implement this feature. The general case is really hard, since you have all sort of compiler optimizations that make it hard to associate a specific line of source code with the generated machine code.

However, some ideas that come to mind:

- Implement stack return address tracking. Whenever you call a function, we'll keep track of the return address in our own, separate stack. When you return from a function / interrupt, we'll check to see if the return address matches the one that we have in our stack. This will make it possible to detect some kind of stack corruptions, but may yield false positives in case of multi-threading.
- If we compile in debug mode (e.g. turn the optimizations off), it's possible that we could use the debugging information (DWARF) to detect anything that looks like an array read/write access. If we are somehow able to figure out the array size as well, this should make it possible to detect out of bounds access at runtime. The general case may still be tricky, since you can always do something like: 
  ```cpp
  char small[16];
  sprintf(small, "Hi, %s", getUserName());
  ```
  then `sprintf` may write beyond the end of the array, and it's unlikely that we can determine the origin of the array and its size inside sprintf (where the actual write happens), but this may help us catch things like:
  ```cpp
  char small[16];
  for (let i = 0; i <=16; i++) { 
    small[i] = i;
  }
  ```

If you have some more ideas how this might be implemented, or thoughts on my ideas above, I'd love to hear them!
