### ISSUE TITLE
ESP32C3 UART Receive Functionality (Rust Embassy)

### ISSUE THREAD

**Issue by apollolabsdev** [wokwi/wokwi-features#713]
In a Rust no-std embassy ESP32C3 example, the UART receiver does not process input read from the terminal to the device UART Rx pin although the input is verified. The input is verified using a logic analyzer monitoring the lines. The analyzer output shows that the expected sequence is being sent to the Rx pin.

This is a Rust embassy example in the following project:
https://wokwi.com/projects/386025413115213825

The example is expected to process the input and print to the monitor the number of bytes that were read.

 - OS: macOS
 - Browser: Both Chrome and Safari

**Some Additional Context:**
- Another thing attempted is to create a loopback on the pins and hard code a transmission sequence. This is to omit the manual input from the monitor. The same behavior remains.
- Testing the same code on different ESP32C3 hardware devkits there are mixed results.

**Comment by urish** [comment]
Thanks for reporting! From local testing, the same issue happens on ESP32-C3-DevKitC-02, so it does not seem like a simulator bug. I tried typing various stuff into the terminal, including Ctrl+D, but no output:

![image](https://github.com/wokwi/wokwi-features/assets/892318/17d16a11-1ad4-4e4a-a424-5079b056ac4e)

**Comment by SergioGasquez** [comment]
Update: I've modified the example: https://wokwi.com/projects/386344438491467777 and now, the generated elf works fine on real HW

**Comment by urish** [comment]
@SergioGasquez Interestingly, it also works in the simulator, but once you input exactly 64 characters followed by a new line: 

e.g. inputting "SWXLHHBJRDKUWXMAFCIJUFVKMNJWMOIYSWXLHHBJRDKUWXMAFCIJUFVKMNJWMOIY" into the text box results in:

![image](https://github.com/wokwi/wokwi-features/assets/892318/4cdb75e5-fd29-46ea-8476-1bf199d12e4a)

Interestingly, the real hardware works very similarly, but with a subtle difference

![image](https://github.com/wokwi/wokwi-features/assets/892318/65404d3b-3188-4d19-9413-2447d91f9710)

note how it says 64 bytes instead of 65 bytes.

Any idea where this 64 / 65 bytes number is coming from? Probably some buffer size, but which?

**Comment by urish** [comment]
As for detecting the end of line condition, I looked at the code and it seems like the issue is that the simulator does not implement the AT CMD functionality that the code uses:

```rust
    uart0.set_at_cmd(AtCmdConfig::new(None, None, None, AT_CMD, None));
```

**Comment by urish** [comment]
AT_CMD fix is up - [@SergioGasquez's project](https://wokwi.com/projects/386344438491467777) should now correctly detect the newlines on Wokwi
