### ISSUE TITLE
WOKWI stops running when another browser tab is selected and used

### ISSUE THREAD

**Issue by systembolaget** [wokwi/wokwi-features#733]
Maybe this is normal behaviour? Or is it some kind of bug? Safari and Firefox macOS.

**Comment by urish** [comment]
Hi! Yeah, this is the normal behaviour - the simulation pauses when the browser tab is not visible. The simulation is resource intensive, so we don't want to end up in a situation where users leave them running in a background tab, forget about them, and then their laptop's battery drains fast because or their computer becomes slow when using other programs.

Do you have a use case where you need to keep the simulation running while the tab is not visible? Note that the browser tab doesn't have to be active - just visible (or partially visible) on the screen.

**Comment by systembolaget** [comment]
Thanks, no, I only wanted to know if this is normal behaviour. All's good.
