### ISSUE TITLE
ESP32 GPIO34-39 INPUT NOT WORKING

### ISSUE THREAD

**Issue by kdirarslan** [wokwi/wokwi-features#827]
Pins 34-39 of Esp32 are not used as input.  I connected the button and also connected the Pull-up and pull-down resistors, but nothing changes.  

I used these pins in the wokwi simulator before, but they became unusable a few weeks ago.

This is a very strange situation.

https://wokwi.com/projects/402769537997757441

**Comment by urish** [comment]
Thanks for the detailed report! Uploaded a fix, can you please try again?

**Comment by kdirarslan** [comment]
thank you problem solved

**Comment by kdirarslan** [comment]
thank you problem solved

**Comment by urish** [comment]
Excellent! The issue happened when we added the PCNT peripheral three weeks ago, as we implemented the FUN_IE bit of the IOMUX RTC. Previously, the IO MUX had the wrong pin count configured on the ESP32, but since FUN_IE wasn't implemented, it didn't cause any issue. Now I fixed the pin count, so the behavior should be correct.

**Comment by kdirarslan** [comment]
I've been having problems with these pins for a while. I hesitated to write about the problem. I didn't think you would solve it in such a short time.
Thank you for your interest.
