### ISSUE TITLE
Add Franzininho C0 board

### ISSUE THREAD

**Issue by Graziele-Rodrigues** [wokwi/wokwi-features#896]
The Franzininho C0 is a development board featuring the STM32C011F6 microcontroller, created to provide an accessible platform for learning and developing embedded systems. It is part of the Franzininho project, which promotes the development of skills in electronics and programming through the DIY format and the maker culture in Brazil.
This board is a great addition to Wokwi, as it can serve educational purposes and expand support for the STM32 family.

- Project URL: [franzininho-c0-board](https://github.com/Franzininho/franzininho-c0-board ) 
- License: CERN Open Hardware License
- Availability: The Franzininho C0 is available for purchase in Brazil through various distributors and is actively developed and supported by the Franzininho community.
- Microcontroller: STM32C011F6 (simulated by Wokwi)
- Board name: franzininho-c0

**Graphics:**
I’m tried to create the SVG file and the board definition in JSON format. If there are any issues or adjustments needed with the initial submission, I’m open to making corrections based on your feedback. 
svg: [link-svg-google-drive](https://drive.google.com/file/d/1rFKB9eFk8FBFroOyy_cyjzxt5nNTTm7i/view?usp=sharing)

![board](https://github.com/user-attachments/assets/2d970534-24a8-42ec-ae00-acdd1823ae44)

json: [link-json-google-drive](https://drive.google.com/file/d/1fdfjlUQ-xA9BxThu61uVUYcHtUDSdD1P/view?usp=sharing 
)
[board.json](https://github.com/user-attachments/files/17342992/board.json)

**Pin naming and layout:**

- Pinout: [pinout-franzininho-c0](https://docs.franzininho.com.br/assets/images/Pinout-Franzininho-C0-34bddd88aa02f5e6d532e774d3d7925a.png)
- Dimension: 38,1 mm x 20.32 mm
- Schematic: [schematic-franzininho-c0](https://docs.franzininho.com.br/assets/images/Franzininho_C0_Schematic-2950216dd4948871d9d70bc01c79d332.png )

**Comment by djedu28** [comment]
Hi @Graziele-Rodrigues.  Very good, excellent contribution! Franzininho really is an excellent low-cost platform for beginners in electronics and robotics.

There are already two Franzininho boards on wokwi (based on [ATtiny85](https://docs.wokwi.com/pt-BR/parts/wokwi-franzininho/) and [esp32-s2](https://docs.wokwi.com/pt-BR/parts/board-franzininho-wifi) )
https://wokwi.com/projects/new#arduino-list
![image](https://github.com/user-attachments/assets/76dd696e-0538-4e75-a893-6539e8265ef7)


As you mentioned, the chicken-c0 version uses STM32C011F6. wokwi already simulates [nucleo-c031c6](https://wokwi.com/projects/new/st-nucleo-c031c6) and [nucleo-l031k6](https://wokwi.com/projects/new/st-nucleo-l031k6)
![image](https://github.com/user-attachments/assets/9babcc33-2452-4d7a-b043-5b5958179cbd)

I'm not familiar with the STM ecosystem, but the codes are different (C011F6 vs C031C6). If they are compatible, then it will be very easy to add this new board, using the same STMC031C6 motor. Otherwise, you'll need to create/adapt the motor for the new version.

Translated with DeepL.com
> Olá @Graziele-Rodrigues.  Muito bom, excelente contribuição! O Franzininho é realmente uma excelente plataforma com baixo custo facilitando iniciantes na eletrônica e robótica.
> 
> Já existem duas boards Franzininho no wokwi (baseadas no [ATtiny85 ](https://docs.wokwi.com/pt-BR/parts/wokwi-franzininho/) e [esp32-s2](https://docs.wokwi.com/pt-BR/parts/board-franzininho-wifi) )
> https://wokwi.com/projects/new#arduino-list
> ![image](https://github.com/user-attachments/assets/76dd696e-0538-4e75-a893-6539e8265ef7)
> 
> 
> Conforme você mencionou, a versão franzininho-c0 usa STM32C011F6. O wokwi já simula o [nucleo-c031c6](https://wokwi.com/projects/new/st-nucleo-c031c6) e [nucleo-l031k6](https://wokwi.com/projects/new/st-nucleo-l031k6)
> ![image](https://github.com/user-attachments/assets/9babcc33-2452-4d7a-b043-5b5958179cbd)
> 
> Não tenho familiaridade com o ecossistema STM, mas os códigos são diferentes (C011F6 vs C031C6). Se forem compatíveis, então será muito fácil adicionar essa nova placa, utilizando o mesmo motor STMC031C6. Caso contrário será necessário criar/adaptar o motor para a nova versão.

**Comment by djedu28** [comment]
The boards have small differences:

|  board | nucleo | -- |
| -- | -- | -- |
| wokwi | c011f6 | https://www.st.com/en/microcontrollers-microprocessors/stm32c011f6.html |
| Franzininho C0 | c031c6 | https://www.st.com/en/microcontrollers-microprocessors/stm32c031c6.html |


|  --| c011f6 | c031c6  | |
| -- | -- | -- | -- |
|  Flash memory | 32 Kbytes | 32 Kbytes |  ✅ |
| RAM | 12 Kbytes | 6 Kbytes | ❌ |
| CPU | 48 MHz | 48 MHz | ✅ |

**Comment by urish** [comment]
Thanks for working on this, I love the Franzininho project and community around it! 

Unfortunately, we don't currently support the STM32C011, and there are no plans to add it, unless someone sponsors the development and support.
